#!/bin/bash
#
# Script for batch co-registration
# V.2 - All files are in the same folder
#     - vtk extension
# cli: launch_testing_registrations fixed_path moving_path masks_path results_path


fixed_path=${1%/}
moving_path=${2%/}
masks_path=${3%/}
results_path=${4%/}

all_cases=$(find $fixed_path -regex ".*\.\(hdr\|vtk\|nii\|nii.gz\)" | grep -Eo '[0-9]+\.' | tr -d '.' | sort -u -k1,1n )

for id in $all_cases
  do
     id_print=$( printf '%02d' $id )

     echo $id_print

     res_path="$results_path/$id_print"

     if [ ! -d $res_path ]; then
       mkdir -p $res_path
     fi

     mri_name=$(ls $fixed_path/xxRM3dT1x$id.* | grep -Ei "(hdr|vtk|nii|nii.gz)" )
     mask_name=$(ls $masks_path/xxRM3dT1x$id.* | grep -Ei "(hdr|vtk|nii|nii.gz)" )
     bas_name=$(ls $moving_path/rec_bas$id_print.* | grep -Ei "(hdr|vtk|nii|nii.gz)" )

     log_file="$results_path/launch_testing_registrations.log"

     eval "echo \"Case $id_print:\" >>  \"$log_file\""
     eval "/usr/bin/time -o \"$log_file\" -a ./vph_reg \"$mri_name\" \"$bas_name\" \"$mask_name\" \"$res_path/\""

done


for i in $results_path/*/tforms.txt
   do 
   tfPath=$(dirname $i)
   tfId=$( echo "$tfPath" | sed -e 's/^.*\([0-9]\{2,3\}\).*$/\1/' )
   eval "cat \"$i\" | sed -e \"s/\\(^# Transform \\)\\([0-9]\\)/\\1${tfId}/\" >> \"$results_path/transforms.tfm\""
done
