#!/bin/bash

images_path=${1%/}
results_path=${2%/}

for case_path in $images_path/*
  do
    case_id=$(echo "$case_path" | sed -e 's/.*\([0-9]\{3\}\).*$/\1/' )

    if [ ! -d "$results_path/$case_id" ]; then
       mkdir -p "$results_path/$case_id"
    fi
    
    command="./maskSpect TSpect.nii $case_path/$case_id-interictal.nii MSpect.nii $case_id-interictal-mask.nii.gz $results_path/$case_id/"
    eval $command

    command2="./maskSpect TSpect.nii $case_path/$case_id-ictal.nii MSpect.nii $case_id-ictal-mask.nii.gz $results_path/$case_id/"
    eval $command2
done
